#!/usr/bin/env bash

. ~/.profile

# Start keychain and unlock our private key. Clear any previously loaded keys - i.e. assume login
# is unauthorised until proven otherwise. Don't ask for passphrases yet - just set it up so that
# when we add keys they're available to everyone. To add a key, do something like:
# `keychain ~/.ssh/id_rsa --nogui`
eval $(keychain --clear --noask --agents ssh --eval)

taffybar &
nm-applet &
owncloud &
qtpass &
# Signal
chromium --app-id=bikioccmkafdpakkkcpdbppfkghcmihk &
parcellite &
xscreensaver --no-splash &
feh --bg-fill ~/wallpapers/current
