#!/usr/bin/env bash

status-notifier-watcher &
GDK_DPI_SCALE=0.8 taffybar &
xembedsniproxy &
nm-applet --sm-disable --indicator &
blueman-applet &
owncloud &
signal-desktop &
parcellite &
xscreensaver -no-splash &
feh --bg-fill ~/wallpapers/current
emacs &
firefox &
thunderbird &
spotify &
volumeicon &
slack &
