#!/usr/bin/env bash

status-notifier-watcher &
taffybar &
nm-applet &
blueman-applet &
owncloud &
signal-desktop &
parcellite &
xscreensaver -no-splash &
feh --bg-fill ~/wallpapers/current
emacs &
firefox &
thunderbird &
spotify &
volumeicon &
slack &
